server:
  port: 8383

spring:
  config:
    import: "optional:configserver:"
  application:
      name: gateway-service
  cloud:
    config:
        discovery:
          enabled: true
          service-id: config-service
    gateway:
      mvc:
        routes:
          - id: checkout-service
            uri: lb://checkout-service
            predicates:
                - Path=/checkout/**
            filters:
              - AddRequestHeader=x-request-from,gateway
              - AddResponseHeader=x-request-from,checkout-service
          - id: products-service
            uri: lb://products-service
            predicates:
                - Path=/products/**












